/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package nhom8.view.user;

import nhom8.view.category.*;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author dell
 */
public class PnlUser extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public PnlUser() {
        initComponents();
    }

    public JLabel getLblAddUser() {
        return lblAddUser;
    }

    public JLabel getLblDeleteUser() {
        return lblDeleteUser;
    }

    public JLabel getLblRefreshUser() {
        return lblRefreshUser;
    }

    public JLabel getLblSearchUser() {
        return lblSearchUser;
    }

    public JLabel getLblUpdateUser() {
        return lblUpdateUser;
    }

    public JTable getTblUser() {
        return tblUser;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblAddUser = new javax.swing.JLabel();
        lblUpdateUser = new javax.swing.JLabel();
        lblDeleteUser = new javax.swing.JLabel();
        lblSearchUser = new javax.swing.JLabel();
        lblRefreshUser = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(536, 100));
        jPanel2.setPreferredSize(new java.awt.Dimension(152, 100));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 20));

        lblAddUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/add.png"))); // NOI18N
        lblAddUser.setText("Thêm");
        lblAddUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblAddUser.setPreferredSize(new java.awt.Dimension(68, 60));
        lblAddUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(lblAddUser);

        lblUpdateUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUpdateUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/edit.png"))); // NOI18N
        lblUpdateUser.setText("Sửa");
        lblUpdateUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblUpdateUser.setPreferredSize(new java.awt.Dimension(68, 60));
        lblUpdateUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(lblUpdateUser);

        lblDeleteUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDeleteUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/delete.png"))); // NOI18N
        lblDeleteUser.setText("Xóa");
        lblDeleteUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblDeleteUser.setPreferredSize(new java.awt.Dimension(68, 60));
        lblDeleteUser.setVerifyInputWhenFocusTarget(false);
        lblDeleteUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(lblDeleteUser);

        lblSearchUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSearchUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/loupe.png"))); // NOI18N
        lblSearchUser.setText("Tìm kiếm");
        lblSearchUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSearchUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(lblSearchUser);

        lblRefreshUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRefreshUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/refresh.png"))); // NOI18N
        lblRefreshUser.setText("Làm mới");
        lblRefreshUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblRefreshUser.setPreferredSize(new java.awt.Dimension(68, 60));
        lblRefreshUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(lblRefreshUser);

        jPanel1.add(jPanel2, "card2");

        add(jPanel1, java.awt.BorderLayout.NORTH);

        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblUser);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddUser;
    private javax.swing.JLabel lblDeleteUser;
    private javax.swing.JLabel lblRefreshUser;
    private javax.swing.JLabel lblSearchUser;
    private javax.swing.JLabel lblUpdateUser;
    private javax.swing.JTable tblUser;
    // End of variables declaration//GEN-END:variables
}
