/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package nhom8.view.product;

/**
 *
 * @author Adminstrator
 */
public class PnlProduct extends javax.swing.JPanel {

    /**
     * Creates new form PnlProduct
     */
    public PnlProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblAddProduct = new javax.swing.JLabel();
        lblEditProduct = new javax.swing.JLabel();
        lblDeleteProduct = new javax.swing.JLabel();
        lblSearchProduct = new javax.swing.JLabel();
        lblRefreshProduct = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 20));

        lblAddProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/add.png"))); // NOI18N
        lblAddProduct.setText("thêm");
        lblAddProduct.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblAddProduct.setPreferredSize(new java.awt.Dimension(68, 60));
        lblAddProduct.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(lblAddProduct);

        lblEditProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEditProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/edit.png"))); // NOI18N
        lblEditProduct.setText("sửa");
        lblEditProduct.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEditProduct.setPreferredSize(new java.awt.Dimension(68, 60));
        lblEditProduct.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(lblEditProduct);

        lblDeleteProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDeleteProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/delete.png"))); // NOI18N
        lblDeleteProduct.setText("xóa");
        lblDeleteProduct.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblDeleteProduct.setMaximumSize(new java.awt.Dimension(68, 60));
        lblDeleteProduct.setMinimumSize(new java.awt.Dimension(68, 60));
        lblDeleteProduct.setPreferredSize(new java.awt.Dimension(68, 60));
        lblDeleteProduct.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(lblDeleteProduct);

        lblSearchProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/loupe.png"))); // NOI18N
        lblSearchProduct.setText("tìm kiếm");
        lblSearchProduct.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSearchProduct.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(lblSearchProduct);

        lblRefreshProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRefreshProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/refresh.png"))); // NOI18N
        lblRefreshProduct.setText("làm mới");
        lblRefreshProduct.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblRefreshProduct.setPreferredSize(new java.awt.Dimension(68, 60));
        lblRefreshProduct.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(lblRefreshProduct);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblProduct);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAddProduct;
    private javax.swing.JLabel lblDeleteProduct;
    private javax.swing.JLabel lblEditProduct;
    private javax.swing.JLabel lblRefreshProduct;
    private javax.swing.JLabel lblSearchProduct;
    private javax.swing.JTable tblProduct;
    // End of variables declaration//GEN-END:variables
}
