/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nhom8.view.home;

import java.awt.Color;
import java.awt.Panel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import nhom8.view.product.PnlProduct;

/**
 * @author minh
 */
public class Dashboard extends javax.swing.JFrame {
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        PnlHome pnl = new PnlHome();
        setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(
                getClass().getResource("/assets/icon_cafe.png")
        ).getImage());
        
        pnlBody.add(pnl);
        pnlBody.repaint();
        pnlBody.revalidate();
    }

    public void setPnlBody(JPanel panel){
        pnlBody.removeAll();
        pnlBody.add(panel);
        pnlBody.repaint();
        pnlBody.revalidate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    public JButton getBtnBill() {
        return btnBill;
    }

    public JButton getBtnCategory() {
        return btnCategory;
    }

    public JButton getBtnDashboard() {
        return btnDashboard;
    }

    public JButton getBtnProduct() {
        return btnProduct;
    }

    public JPanel getPnlBody() {
        return pnlBody;
    }

    public JPanel getPnlBorderBill() {
        return pnlBorderBill;
    }

    public JPanel getPnlBorderCategory() {
        return pnlBorderCategory;
    }

    public JPanel getPnlBorderDashboard() {
        return pnlBorderDashboard;
    }

    public JPanel getPnlBorderProduct() {
        return pnlBorderProduct;
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        pnlDashboardMenu = new javax.swing.JPanel();
        pnlBorderDashboard = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        pnlCategoryMenu = new javax.swing.JPanel();
        pnlBorderCategory = new javax.swing.JPanel();
        btnCategory = new javax.swing.JButton();
        pnlProductMenu = new javax.swing.JPanel();
        pnlBorderProduct = new javax.swing.JPanel();
        btnProduct = new javax.swing.JButton();
        pnlBillMenu = new javax.swing.JPanel();
        pnlBorderBill = new javax.swing.JPanel();
        btnBill = new javax.swing.JButton();
        pnlBody = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Coffee Shop Management");
        setPreferredSize(new java.awt.Dimension(1138, 800));
        setSize(new java.awt.Dimension(1138, 800));
        getContentPane().setLayout(new java.awt.CardLayout());

        pnlHeader.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        pnlDashboardMenu.setBackground(new java.awt.Color(255, 255, 255));
        pnlDashboardMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pnlBorderDashboard.setBackground(new java.awt.Color(51, 204, 0));

        javax.swing.GroupLayout pnlBorderDashboardLayout = new javax.swing.GroupLayout(pnlBorderDashboard);
        pnlBorderDashboard.setLayout(pnlBorderDashboardLayout);
        pnlBorderDashboardLayout.setHorizontalGroup(
            pnlBorderDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 134, Short.MAX_VALUE)
        );
        pnlBorderDashboardLayout.setVerticalGroup(
            pnlBorderDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        btnDashboard.setText("Dashboard");
        btnDashboard.setBorder(null);
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDashboardMenuLayout = new javax.swing.GroupLayout(pnlDashboardMenu);
        pnlDashboardMenu.setLayout(pnlDashboardMenuLayout);
        pnlDashboardMenuLayout.setHorizontalGroup(
            pnlDashboardMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBorderDashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlDashboardMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlDashboardMenuLayout.createSequentialGroup()
                    .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnlDashboardMenuLayout.setVerticalGroup(
            pnlDashboardMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardMenuLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(pnlBorderDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlDashboardMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlDashboardMenuLayout.createSequentialGroup()
                    .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel5.add(pnlDashboardMenu);

        pnlCategoryMenu.setBackground(new java.awt.Color(255, 255, 255));
        pnlCategoryMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pnlBorderCategory.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlBorderCategoryLayout = new javax.swing.GroupLayout(pnlBorderCategory);
        pnlBorderCategory.setLayout(pnlBorderCategoryLayout);
        pnlBorderCategoryLayout.setHorizontalGroup(
            pnlBorderCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 134, Short.MAX_VALUE)
        );
        pnlBorderCategoryLayout.setVerticalGroup(
            pnlBorderCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        btnCategory.setText("Category");
        btnCategory.setBorder(null);
        btnCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCategoryMenuLayout = new javax.swing.GroupLayout(pnlCategoryMenu);
        pnlCategoryMenu.setLayout(pnlCategoryMenuLayout);
        pnlCategoryMenuLayout.setHorizontalGroup(
            pnlCategoryMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBorderCategory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlCategoryMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCategoryMenuLayout.createSequentialGroup()
                    .addComponent(btnCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnlCategoryMenuLayout.setVerticalGroup(
            pnlCategoryMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCategoryMenuLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(pnlBorderCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlCategoryMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCategoryMenuLayout.createSequentialGroup()
                    .addComponent(btnCategory, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel5.add(pnlCategoryMenu);

        pnlProductMenu.setBackground(new java.awt.Color(255, 255, 255));
        pnlProductMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pnlBorderProduct.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlBorderProductLayout = new javax.swing.GroupLayout(pnlBorderProduct);
        pnlBorderProduct.setLayout(pnlBorderProductLayout);
        pnlBorderProductLayout.setHorizontalGroup(
            pnlBorderProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 134, Short.MAX_VALUE)
        );
        pnlBorderProductLayout.setVerticalGroup(
            pnlBorderProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        btnProduct.setText("Product");
        btnProduct.setBorder(null);
        btnProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlProductMenuLayout = new javax.swing.GroupLayout(pnlProductMenu);
        pnlProductMenu.setLayout(pnlProductMenuLayout);
        pnlProductMenuLayout.setHorizontalGroup(
            pnlProductMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBorderProduct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlProductMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlProductMenuLayout.createSequentialGroup()
                    .addComponent(btnProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnlProductMenuLayout.setVerticalGroup(
            pnlProductMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductMenuLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(pnlBorderProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlProductMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlProductMenuLayout.createSequentialGroup()
                    .addComponent(btnProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel5.add(pnlProductMenu);

        pnlBillMenu.setBackground(new java.awt.Color(255, 255, 255));
        pnlBillMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pnlBorderBill.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlBorderBillLayout = new javax.swing.GroupLayout(pnlBorderBill);
        pnlBorderBill.setLayout(pnlBorderBillLayout);
        pnlBorderBillLayout.setHorizontalGroup(
            pnlBorderBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 134, Short.MAX_VALUE)
        );
        pnlBorderBillLayout.setVerticalGroup(
            pnlBorderBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        btnBill.setText("Bill");
        btnBill.setBorder(null);
        btnBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBillMenuLayout = new javax.swing.GroupLayout(pnlBillMenu);
        pnlBillMenu.setLayout(pnlBillMenuLayout);
        pnlBillMenuLayout.setHorizontalGroup(
            pnlBillMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBorderBill, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlBillMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlBillMenuLayout.createSequentialGroup()
                    .addComponent(btnBill, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnlBillMenuLayout.setVerticalGroup(
            pnlBillMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBillMenuLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(pnlBorderBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlBillMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlBillMenuLayout.createSequentialGroup()
                    .addComponent(btnBill, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel5.add(pnlBillMenu);

        pnlHeader.add(jPanel5, java.awt.BorderLayout.NORTH);

        pnlBody.setBackground(new java.awt.Color(255, 255, 255));
        pnlBody.setMinimumSize(new java.awt.Dimension(1000, 800));
        pnlBody.setPreferredSize(new java.awt.Dimension(1000, 800));
        pnlBody.setLayout(new java.awt.CardLayout());
        pnlHeader.add(pnlBody, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlHeader, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        pnlBorderDashboard.setBackground(new Color(51,204,0));
        
        pnlBorderCategory.setBackground(new Color(255,255, 255));
        pnlBorderProduct.setBackground(new Color(255,255, 255));
        pnlBorderBill.setBackground(new Color(255,255, 255));
        
        pnlBody.removeAll();
        PnlHome pnl = new PnlHome();
        
        pnlBody.add(pnl);
        pnlBody.repaint();
        pnlBody.revalidate();
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryActionPerformed
        pnlBorderCategory.setBackground(new Color(51,204,0));
        
        pnlBorderDashboard.setBackground(new Color(255,255, 255));
        pnlBorderProduct.setBackground(new Color(255,255, 255));
        pnlBorderBill.setBackground(new Color(255,255, 255));
    }//GEN-LAST:event_btnCategoryActionPerformed

    private void btnProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductActionPerformed
        pnlBorderProduct.setBackground(new Color(51,204,0));
        
        pnlBorderDashboard.setBackground(new Color(255,255, 255));
        pnlBorderCategory.setBackground(new Color(255,255, 255));
        pnlBorderBill.setBackground(new Color(255,255, 255));
    }//GEN-LAST:event_btnProductActionPerformed

    private void btnBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillActionPerformed
        // TODO add your handling code here:
        pnlBorderBill.setBackground(new Color(51,204,0));
        
        pnlBorderDashboard.setBackground(new Color(255,255, 255));
        pnlBorderCategory.setBackground(new Color(255,255, 255));
        pnlBorderProduct.setBackground(new Color(255,255, 255));
    }//GEN-LAST:event_btnBillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                 javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Dashboard().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBill;
    private javax.swing.JButton btnCategory;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnProduct;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel pnlBillMenu;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlBorderBill;
    private javax.swing.JPanel pnlBorderCategory;
    private javax.swing.JPanel pnlBorderDashboard;
    private javax.swing.JPanel pnlBorderProduct;
    private javax.swing.JPanel pnlCategoryMenu;
    private javax.swing.JPanel pnlDashboardMenu;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlProductMenu;
    // End of variables declaration//GEN-END:variables
}
